import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/footer/Footer";
import Header from "@/components/layout/header/Header";
import { Suspense } from "react";
// import { Cinzel } from "next/font/google";

// export const cinzel = Cinzel({
//   subsets: ["latin"],
//   weight: ["500", "600", "700"],
// });




export const inter = Inter({ subsets: ['latin'], weight: ["400", "700"] })

export const metadata: Metadata = {
  title: {
    default: "MTG shop",
    template: "%s | MTG",
    absolute: "",
  },
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={null}>
          <Header />
        </Suspense>
          {children}
        <Suspense fallback={null}>
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}



