import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Footer from "@/components/layout/footer/Footer";
// import Header from "@/components/layout/header/Header";



const inter = Inter({ subsets: ['latin'], weight: ["400", "700"] })

export const metadata: Metadata = {
  title: {
    default: "MTG shop",
    template: "%s | MTG",
    absolute: "",
  },
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Header /> */}
          {children}
        {/* <Footer/> */}
      </body>
    </html>
  );
}



